// mockData.ts
export interface InventoryItem {
  clave: string;
  descripcion: string;
  ubicacion: string;
  usoEn: string;
  usoEn2: string;
  proveedores: string;
  fotos: boolean;
}

export const MOCK_DATA: InventoryItem[] = [
  // --- INICIO DE DATOS REALES (200+ ITEMS) ---
  {
    clave: 'R0929',
    descripcion: 'CHUMACERA DE PISO DE 5/8 SKF',
    ubicacion: 'TABLA#74',
    usoEn: 'AUTING',
    usoEn2: '',
    proveedores: 'REPRESENTACIONES INDUSTRIALES',
    fotos: true,
  },
  {
    clave: 'R0936',
    descripcion: 'AJUSTADOR DE CADENA #22RO11/25 (H)',
    ubicacion: 'ANAQ. LAMINA #2 / L#2-C#1',
    usoEn: 'MONDINIS (HARPAK) CADENA JARABERA',
    usoEn2: '',
    proveedores: 'HARPAK',
    fotos: true,
  },
  {
    clave: 'R0937',
    descripcion: 'PANEL VIEW PLUS 700 #2711P-RDT7C/A (INTERC)®',
    ubicacion: 'TABLA #13',
    usoEn: 'SIN MOVIMIENTO',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: false,
  },
  {
    clave: 'R0938',
    descripcion: 'CABLE HEMBRA #48XZCP1141L5 (H)',
    ubicacion: 'ANAQ. LAMINA #2 / L#2-C#5',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'HARPAK',
    fotos: true,
  },
  {
    clave: 'R0939',
    descripcion: 'CIRCUITO MODULO #481746HT (H)',
    ubicacion: 'TABLA #15',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'HARPAK',
    fotos: true,
  },
  {
    clave: 'R0940',
    descripcion: 'FLECHA #71HF50040200 (H)',
    ubicacion: 'TABLA #8',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'HARPAK',
    fotos: false,
  },
  {
    clave: 'R0941',
    descripcion: 'FRENO ELECTROMAGNETICO # 24FRENOCOELH1 H',
    ubicacion: 'TABLA #50',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: true,
  },
  {
    clave: 'R0942',
    descripcion: 'RETEN #28RS30X40X7 (H)',
    ubicacion: 'CAJA PLASTICA #A-15',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'HARPAK',
    fotos: true,
  },
  {
    clave: 'R0943',
    descripcion: 'SEÑALIZADOR DE POSICION #44R158AS41TG (H)',
    ubicacion: 'OBSOLETO',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: false,
  },
  {
    clave: 'R0944',
    descripcion: 'TERMINALES #25GIKFR25PB (H)',
    ubicacion: 'ANAQ. LAMINA #2 / L#2-C#1',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'HARPAK',
    fotos: true,
  },
  {
    clave: 'R0945',
    descripcion: 'CABEZAL BAJO #240935A DE 75x16mm (F)',
    ubicacion: 'OBSOLETO',
    usoEn: 'CERRADORA 24/20oz (FOWLER)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: false,
  },
  {
    clave: 'R0946',
    descripcion: 'CAJA VELOCIDAD #21110P80402028 (H)',
    ubicacion: 'TABLA #51',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'HARPAK',
    fotos: true,
  },
  {
    clave: 'R0947',
    descripcion: 'CLUTCH FRENO ELECTROMAGNETICO',
    ubicacion: 'OBSOLETO',
    usoEn: 'SIN USO REGISTRADO',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: false,
  },
  {
    clave: 'R0948',
    descripcion: 'MOTOR CON FRENO TYPE-F90LC4 #210250420000A3 (H)',
    ubicacion: 'TABLA #51',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'HARPAK / NORMA LETICIA GARZA L.',
    fotos: true,
  },
  {
    clave: 'R0949',
    descripcion: 'MANGUERA 20mm #34ARMOVIN20 (H)',
    ubicacion: 'TABLA #1',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'ALFA Y OMEGA / HARPAK',
    fotos: true,
  },
  {
    clave: 'R0950',
    descripcion: 'MANGUERA 40mm #34ARMOVIN40 (H)',
    ubicacion: 'TABLA #1',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'ALFA Y OMEGA / HARPAK',
    fotos: true,
  },
  {
    clave: 'R0951',
    descripcion: 'REFLECTOR 45CATAR180x40 (H)',
    ubicacion: 'ANAQ. LAMINA #2 / L#3-C#1',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'CONTROL SENSORS / HARPAK',
    fotos: true,
  },
  {
    clave: 'R0952',
    descripcion: 'RODILLO PRESION DE GOMA #032957 A',
    ubicacion: 'OBSOLETO',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: false,
  },
  {
    clave: 'R0953',
    descripcion: 'BALERO #15102 DE CONO',
    ubicacion: 'ANAQ. LAMINA #8 / L#11-C#1',
    usoEn: 'BALEROS (USO GENERAL)',
    usoEn2: '',
    proveedores: 'RIRSA/RYASA',
    fotos: true,
  },
  {
    clave: 'R0954',
    descripcion: 'ALIMENTADOR ESTRELLA # DSR-0220 (EL)',
    ubicacion: 'TABLA #34',
    usoEn: 'JARABEADORA ELMAR (24/20oz)',
    usoEn2: '',
    proveedores: 'ELMAR 20oz',
    fotos: true,
  },
  {
    clave: 'R0955',
    descripcion: 'ARANDELA #ASR-0034 (EL)',
    ubicacion: 'CAJA PLASTICA #G-1',
    usoEn: 'JARABEADORA ELMAR (24/20oz)',
    usoEn2: '',
    proveedores: 'ELMAR 20oz',
    fotos: true,
  },
  {
    clave: 'R0956',
    descripcion: 'BANDA ESPACIADORA #27FN15E210x1300 (H)',
    ubicacion: 'ANAQ. LAMINA #11 / L#2',
    usoEn: 'MONDINI 1',
    usoEn2: '',
    proveedores: 'LINARAND',
    fotos: true,
  },
  {
    clave: 'R0957',
    descripcion: 'CAJA VELOCIDADES #21070F30282019 (H)',
    ubicacion: 'TABLA #50',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'HARPAK',
    fotos: true,
  },
  {
    clave: 'R0958',
    descripcion: 'CONTROL VELOCIDAD #4RI58AS41TG (H)',
    ubicacion: 'ANAQ. LAMINA #2 / L#3-C#2',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: true,
  },
  {
    clave: 'R0959',
    descripcion: 'FLECHA METALICA #71HE50018100 (H)',
    ubicacion: 'TABLA #8',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'HARPAK',
    fotos: true,
  },
  {
    clave: 'R0960',
    descripcion: 'REELEVADOR #42HC224DC (H)',
    ubicacion: 'CAJA PLASTICA #A-6',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'INSTRUMENTACION RG',
    fotos: true,
  },
  {
    clave: 'R0961',
    descripcion: 'RESORTES #24MLCK.5.17/N (H)',
    ubicacion: 'TABLA #4',
    usoEn: 'MONDINI #2 (HARPAK)',
    usoEn2: '',
    proveedores: 'HARPAK',
    fotos: true,
  },
  {
    clave: 'R0962',
    descripcion: 'RETEN #28G20X26X4 (H)',
    ubicacion: 'CAJA PLASTICA #A-15',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'RIRSA / RYASA',
    fotos: true,
  },
  {
    clave: 'R0963',
    descripcion: 'RUEDAS DENTADAS #71LN00300300 (H)',
    ubicacion: 'TABLA #2',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'HARPAK',
    fotos: true,
  },
  {
    clave: 'R0964',
    descripcion: 'ARANDELA #032780 (A)',
    ubicacion: 'OBSOLETO',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: true,
  },
  {
    clave: 'R0965',
    descripcion: 'BANDA #009478 (A)',
    ubicacion: 'OBSOLETO',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: true,
  },
  {
    clave: 'R0966',
    descripcion: 'BANDA #014064 (A)',
    ubicacion: 'OBSOLETO',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: false,
  },
  {
    clave: 'R0967',
    descripcion: 'BANDA 600H150 #050042 (A)',
    ubicacion: 'OBSOLETO',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: false,
  },
  {
    clave: 'R0968',
    descripcion: 'CABLE DE CONEXION #072819 (A)',
    ubicacion: 'A. GRAINGER #2 / L#1-C#2',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'ACCRAPLY',
    fotos: true,
  },
  {
    clave: 'R0969',
    descripcion: 'CABLE DE FIBRA OPTICA #010651 (A)',
    ubicacion: 'OBSOLETO',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: false,
  },
  {
    clave: 'R0970',
    descripcion: 'COPLES #001217 (A) (CHICOS)',
    ubicacion: 'OBSOLETO',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: false,
  },
  {
    clave: 'R0971',
    descripcion: 'COPLES #009898 (A) (GRANDES)',
    ubicacion: 'OBSOLETO',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: false,
  },
  {
    clave: 'R0972',
    descripcion: 'FUENTE DE PODER #028805 (A)',
    ubicacion: 'OBSOLETO',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: false,
  },
  {
    clave: 'R0973',
    descripcion: 'FUSIBLE DE 1 AMP. #016645 (A)',
    ubicacion: 'OBSOLETO',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: true,
  },
  {
    clave: 'R0974',
    descripcion: 'FUSIBLE DE 4 AMP. #038263 (A)',
    ubicacion: 'OBSOLETO',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: true,
  },
  {
    clave: 'R0975',
    descripcion: 'REELEVADOR #004517 12 VDC. 4PDT. (A)',
    ubicacion: 'OBSOLETO',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: true,
  },
  {
    clave: 'R0976',
    descripcion: 'RESORTE #001212 (A)',
    ubicacion: 'OBSOLETO',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: true,
  },
  {
    clave: 'R0977',
    descripcion: 'RESORTE #004366 (A)',
    ubicacion: 'CAJA PLASTICA #C-1',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'ACCRAPLY',
    fotos: true,
  },
  {
    clave: 'R0978',
    descripcion: 'RESORTE #006047 (A)',
    ubicacion: 'OBSOLETO',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: true,
  },
  {
    clave: 'R0979',
    descripcion: 'RESORTE #008372 (A)',
    ubicacion: 'CAJA PLASTICA #C-1',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'ACCRAPLY',
    fotos: true,
  },
  {
    clave: 'R0980',
    descripcion: 'RESORTE #033611 (A)',
    ubicacion: 'CAJA PLASTICA #C-1',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'ACCRAPLY',
    fotos: true,
  },
  {
    clave: 'R0981',
    descripcion: 'RESORTE #071034 (A)',
    ubicacion: 'ANAQ. LAMINA #6 / L#10-C#2',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'ACCRAPLY',
    fotos: true,
  },
  {
    clave: 'R0982',
    descripcion: 'RESORTE #071035 (A)',
    ubicacion: 'ANAQ. LAMINA #6 / L#10-C#2',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'ACCRAPLY',
    fotos: true,
  },
  {
    clave: 'R0983',
    descripcion: 'TRASMICION DE VELOCIDADES #012545 (A)',
    ubicacion: 'TABLA #24',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'ACCRAPLY',
    fotos: true,
  },
  {
    clave: 'R0984',
    descripcion: 'SENSOR DE PROX. (Bi1,5U-EG08-AP6X) MCA-TURK #106843 (A)',
    ubicacion: 'ANAQ. LAMINA #6 / L#10-C#3',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'ACCRAPLY',
    fotos: true,
  },
  {
    clave: 'R0985',
    descripcion: 'SENSOR DE PROXIMIDAD #100069 (A)',
    ubicacion: 'CAJA PLASTICA #C-1',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'ACCRAPLY',
    fotos: true,
  },
  {
    clave: 'R0986',
    descripcion: 'SENSOR DE PROXIMIDAD #720490 (A)',
    ubicacion: 'OBSOLETO',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: false,
  },
  {
    clave: 'R0987',
    descripcion: 'ADAPTADOR INOX T-304 P/ABRELATAS # 825/625 (A014)',
    ubicacion: 'A. GRAINGER #4 / L#1-C#1',
    usoEn: 'ABRELATAS (EDLUND)',
    usoEn2: '',
    proveedores: 'EDLUND / HERITAGE',
    fotos: true,
  },
  {
    clave: 'R0988',
    descripcion: 'BASE METALICO DE SEG. # 10.603 (C084H) E',
    ubicacion: 'A. GRAINGER #4 / L#1-C#1',
    usoEn: 'ABRELATAS (EDLUND)',
    usoEn2: '',
    proveedores: 'EDLUND / HERITAGE',
    fotos: true,
  },
  {
    clave: 'R0989',
    descripcion: 'FILTRO HIDRAULICO # 51551 (F034) (E)',
    ubicacion: 'TABLA #28',
    usoEn: 'ABRELATAS (EDLUND)',
    usoEn2: '',
    proveedores: 'EDLUND / HERITAGE',
    fotos: true,
  },
  {
    clave: 'R0990',
    descripcion: 'INTERRUPTOR PRESS. 1300 PSI (S250A) E',
    ubicacion: 'A. GRAINGER #4 / L#1-C#2',
    usoEn: 'ABRELATAS (EDLUND)',
    usoEn2: '',
    proveedores: 'EDLUND / HERITAGE',
    fotos: true,
  },
  {
    clave: 'R0991',
    descripcion: 'SENSOR DE PROX. 12mm. (S3050B) #E-S1TMU/4AN (S477)',
    ubicacion: 'ANAQ. LAMINA #7 / L#3-C#1',
    usoEn: 'ABRELATAS (EDLUND)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: true,
  },
  {
    clave: 'R0992',
    descripcion: 'SENSOR DE PROX. 18mm (S3460) #E-A2TMU/4AN (S474)',
    ubicacion: 'ANAQ. LAMINA #7 / L#3-C#1',
    usoEn: 'ABRELATAS (EDLUND)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: true,
  },
  {
    clave: 'R0993',
    descripcion: 'INTERRUPTOR PROXIMIDAD 24VDC30MM',
    ubicacion: 'OBSOLETO',
    usoEn: 'ABRELATAS (EDLUND)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: false,
  },
  {
    clave: 'R0994',
    descripcion: 'SENSOR DE PROX. 30mm (S3470) #E-A3TMU/4AN (S470)',
    ubicacion: 'ANAQ. LAMINA #7 / L#3-C#1',
    usoEn: 'ABRELATAS (EDLUND)',
    usoEn2: '',
    proveedores: 'EDLUND / HERITAGE',
    fotos: true,
  },
  {
    clave: 'R0995',
    descripcion: 'INTERRUPTOR PROXIMIDAD C-151 (S475) E',
    ubicacion: 'OBSOLETO',
    usoEn: 'ABRELATAS (EDLUND)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: false,
  },
  {
    clave: 'R0996',
    descripcion: 'INTERRUPTOR DE PROX. MCA-SMC #D-A73L (3 MTS)',
    ubicacion: 'ANAQ. LAMINA #7 / L#3-C#2',
    usoEn: 'ABRELATAS (EDLUND)',
    usoEn2: '',
    proveedores: 'CONTROL SENSORS',
    fotos: true,
  },
  {
    clave: 'R0997',
    descripcion: 'INTERRUPTOR DE PROX. MCA-STARCYL #762.000.004',
    ubicacion: 'ANAQ. LAMINA #7 / L#3-C#2',
    usoEn: 'ABRELATAS (EDLUND)',
    usoEn2: '',
    proveedores: 'EDLUND / HERITAGE',
    fotos: true,
  },
  {
    clave: 'R0998',
    descripcion: 'NAVAJA CIRCULAR # 825/625 600 DIA-A807E',
    ubicacion: 'TABLA #28',
    usoEn: 'ABRELATAS (EDLUND)',
    usoEn2: '',
    proveedores: 'EDLUND / HERITAGE',
    fotos: true,
  },
  {
    clave: 'R0999',
    descripcion: "PASADOR METALICO B043 A3x6' (P384) E",
    ubicacion: 'A. GRAINGER #4 / L#1-C#2',
    usoEn: 'ABRELATAS (EDLUND)',
    usoEn2: '',
    proveedores: 'EDLUND / HERITAGE',
    fotos: true,
  },
  {
    clave: 'R1000',
    descripcion: 'PISTON CILIND. MCA-STARCYL (ST3F1-5X2.5)',
    ubicacion: 'TABLA #29',
    usoEn: 'ABRELATAS (EDLUND)',
    usoEn2: '',
    proveedores: 'EDLUND / HERITAGE',
    fotos: true,
  },
  {
    clave: 'R1001',
    descripcion: 'PISTON CILINDRICO 1-1/8x1 SMT (C152) E',
    ubicacion: 'ANAQ. LAMINA #7 / L#3-C#3',
    usoEn: 'ABRELATAS (EDLUND)',
    usoEn2: '',
    proveedores: 'EDLUND / HERITAGE',
    fotos: true,
  },
  {
    clave: 'R1002',
    descripcion: 'PISTON CILIND. MCA-STARCYL (ST5F5-2.00X07.00X1.38)',
    ubicacion: 'TABLA #29',
    usoEn: 'ABRELATAS (EDLUND)',
    usoEn2: '',
    proveedores: 'RAUL MORENO VELDARRAIN',
    fotos: true,
  },
  {
    clave: 'R1003',
    descripcion: 'PISTON CILIND. #RSDQB50-UIA9810 MCA-SMC (C163)',
    ubicacion: 'TABLA #28',
    usoEn: 'ABRELATAS (EDLUND)',
    usoEn2: '',
    proveedores: 'EDLUND / HERITAGE',
    fotos: true,
  },
  {
    clave: 'R1004',
    descripcion: 'PISTON CILINDRICO 950 PUSHER AIR (C296)',
    ubicacion: 'TABLA #28',
    usoEn: 'ABRELATAS (EDLUND)',
    usoEn2: '',
    proveedores: 'EDLUND / HERITAGE',
    fotos: true,
  },
  {
    clave: 'R1005',
    descripcion: 'PISTON CILINDRICO ALG. 1-1/16x1 MCA-SMC',
    ubicacion: 'ANAQ. LAMINA #7 / L#3-C#3',
    usoEn: 'ABRELATAS (EDLUND)',
    usoEn2: '',
    proveedores: 'RAUL MORENO V / INSTRUMENTACION RG',
    fotos: true,
  },
  {
    clave: 'R1006',
    descripcion: 'PISTON CILINDRICO #CDQ2B63-50DZ MCA-SMC',
    ubicacion: 'ANAQ. LAMINA #7 / L#3-C#3',
    usoEn: 'ABRELATAS (EDLUND)',
    usoEn2: '',
    proveedores: 'EDLUND / HERITAGE',
    fotos: true,
  },
  {
    clave: 'R1007',
    descripcion: 'VALVULA DE PASO MJTV-3 (V027) E',
    ubicacion: 'A. GRAINGER #4 / L#1-C#3',
    usoEn: 'ABRELATAS (EDLUND)',
    usoEn2: '',
    proveedores: 'INSTRUMENTACION RG.',
    fotos: true,
  },
  {
    clave: 'R1008',
    descripcion: 'POLEA MARTIN # 14L050 (RIR)',
    ubicacion: 'ANAQ. LAM. PLOMERIA #8 / L#2',
    usoEn: 'CHECADOR DE PESOS',
    usoEn2: '',
    proveedores: 'RIRSA/RYASA',
    fotos: true,
  },
  {
    clave: 'R1009',
    descripcion: 'CHUMACERA DE PARED #FYTB 20 TF (RIR)',
    ubicacion: 'ANAQ. LAM. PLOMERIA #8 / L#2',
    usoEn: 'CHECADOR DE PESOS',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: true,
  },
  {
    clave: 'R1010',
    descripcion: 'ADITIVO #5199 P/IMPRESORAS IMAJE (MI)',
    ubicacion: 'GABINETE PROD. NO ALIMENTICIO',
    usoEn: 'IMPRESORAS IMAJE',
    usoEn2: '',
    proveedores: 'MARKEM IMAJE',
    fotos: true,
  },
  {
    clave: 'R1011',
    descripcion: 'TINTA NEGRA PARA IMPRESORA #5135E',
    ubicacion: 'OBSOLETO',
    usoEn: 'IMPRESORAS IMAJE',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: false,
  },
  {
    clave: 'R1012',
    descripcion: 'FUENTE DE PODER P/DEVICENT #SDN4-24-10LP',
    ubicacion: 'GABINETE RISOUL (RESGUARDO)',
    usoEn: 'SIN MOVIMIENTO',
    usoEn2: '',
    proveedores: 'RISOUL',
    fotos: true,
  },
  {
    clave: 'R1013',
    descripcion: 'POWERFLEX-40 240 VCA 3HP #22B-B012N104TL',
    ubicacion: 'GABINETE RISOUL (RESGUARDO)',
    usoEn: 'SIN MOVIMIENTO',
    usoEn2: '',
    proveedores: 'RISOUL',
    fotos: true,
  },
  {
    clave: 'R1014',
    descripcion: 'SENSOR INDUCTIVO 1mm SE# 872C-MM1NP7-E2',
    ubicacion: 'A. GRAINGER #7 / L#1-C#1',
    usoEn: 'SIN MOVIMIENTO',
    usoEn2: '',
    proveedores: 'RISOUL',
    fotos: true,
  },
  {
    clave: 'R1015',
    descripcion: 'SENSOR INDUCTIVO 3mm SE#872C-D3NP12-E2',
    ubicacion: 'A. GRAINGER #7 / L#1-C#1',
    usoEn: 'MONDINIS',
    usoEn2: '',
    proveedores: 'RISOUL',
    fotos: true,
  },
  {
    clave: 'R1016',
    descripcion: 'VARIADOR DE FRECUENCIA P.F.#22A-B8P0N104',
    ubicacion: 'GABINETE RISOUL (RESGUARDO)',
    usoEn: 'BANDAS PRODUCCION',
    usoEn2: '',
    proveedores: 'RISOUL',
    fotos: true,
  },
  {
    clave: 'R1017',
    descripcion: 'VARIADOR DE FRECUENCIA P.F.#22A-D4P0N104',
    ubicacion: 'GABINETE RISOUL (RESGUARDO)',
    usoEn: 'BANDAS TRANSP. DE CHAROLAS 8oz',
    usoEn2: '',
    proveedores: 'RISOUL',
    fotos: true,
  },
  {
    clave: 'R1018',
    descripcion: 'VARIADOR DE FRECUENCIA P.F.#22A-D1P4N104',
    ubicacion: 'GABINETE RISOUL (RESGUARDO)',
    usoEn: 'WALDNER Y ORION',
    usoEn2: '',
    proveedores: 'RISOUL',
    fotos: true,
  },
  {
    clave: 'R1019',
    descripcion: 'ARRANCADOR MANUAL Y PROTEC.#140M-C2E-B16',
    ubicacion: 'ANAQ. LAMINA #4 / L#3-C#2',
    usoEn: 'TABLEROS ELECTRICOS',
    usoEn2: '',
    proveedores: 'RISOUL',
    fotos: true,
  },
  {
    clave: 'R1020',
    descripcion: 'CONTACTOR IEC PA. 3 POLOS #100-C09D10.AB',
    ubicacion: 'ANAQ. LAMINA #4 / L#4-C#4',
    usoEn: 'TABLEROS ELECTRICOS',
    usoEn2: '',
    proveedores: 'RISOUL',
    fotos: true,
  },
  {
    clave: 'R1021',
    descripcion: 'ARANDELA METALICA #60168502A (F)',
    ubicacion: 'ANAQ. LAMINA #5 / L#2-C#3',
    usoEn: 'CERRADORA 24/20oz (FOWLER)',
    usoEn2: '',
    proveedores: 'ZALKIN',
    fotos: true,
  },
  {
    clave: 'R1022',
    descripcion: 'BANDA ENTRADA #27FAB2E210x1315 (H)',
    ubicacion: 'ANAQ. LAMINA #11 / L#2',
    usoEn: 'MONDINI 1',
    usoEn2: '',
    proveedores: 'LINARAND',
    fotos: true,
  },
  {
    clave: 'R1023',
    descripcion: 'BANDA ESPACIADORA #27FAW5E100x1775 (H)',
    ubicacion: 'ANAQ. LAMINA #11 / L#2',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'LINARAND',
    fotos: true,
  },
  {
    clave: 'R1024',
    descripcion: 'BASE ARTICULADA METALICA #60611063 (F)',
    ubicacion: 'ANAQ. LAMINA #5 / L#1-C#1',
    usoEn: 'CERRADORA 24/20oz (FOWLER)',
    usoEn2: '',
    proveedores: 'ZALKIN',
    fotos: true,
  },
  {
    clave: 'R1025',
    descripcion: 'CONECTORES METALICOS #60315658 (F)',
    ubicacion: 'CAJA PLASTICA #F-1',
    usoEn: 'CERRADORA 24/20oz (FOWLER)',
    usoEn2: '',
    proveedores: 'ZALKIN',
    fotos: true,
  },
  {
    clave: 'R1026',
    descripcion: 'CONECTORES METALICOS #60315659 (F)',
    ubicacion: 'CAJA PLASTICA #F-1',
    usoEn: 'CERRADORA 24/20oz (FOWLER)',
    usoEn2: '',
    proveedores: 'ZALKIN',
    fotos: true,
  },
  {
    clave: 'R1027',
    descripcion: 'DISPENSADOR METALICO #60611059(F)',
    ubicacion: 'TABLA #32',
    usoEn: 'CERRADORA 24/20oz (FOWLER)',
    usoEn2: '',
    proveedores: 'ZALKIN',
    fotos: true,
  },
  {
    clave: 'R1028',
    descripcion: 'ARANDELA # ASR-0075 (EL)',
    ubicacion: 'CAJA PLASTICA #G-1',
    usoEn: 'JARABEADORA ELMAR (20/24oz)',
    usoEn2: '',
    proveedores: 'ELMAR 20oz',
    fotos: true,
  },
  {
    clave: 'R1029',
    descripcion: 'LLAVE TURN HOLD DOWN #60B6849-02 (F)',
    ubicacion: 'ANAQ. LAMINA #5 / L#1-C#2',
    usoEn: 'CERRADORA 24/20oz (FOWLER)',
    usoEn2: '',
    proveedores: 'ZALKIN',
    fotos: true,
  },
  {
    clave: 'R1030',
    descripcion: 'LLAVE TURN HOLD DOWN #60B6849-03 (F)',
    ubicacion: 'ANAQ. LAMINA #5 / L#1-C#2',
    usoEn: 'CERRADORA 24/20oz (FOWLER)',
    usoEn2: '',
    proveedores: 'ZALKIN',
    fotos: true,
  },
  {
    clave: 'R1031',
    descripcion: 'PISTON NEUMATICO #60321359 (F)',
    ubicacion: 'ANAQ. LAMINA #5 / L#1-C#1',
    usoEn: 'CERRADORA 24/20oz (FOWLER)',
    usoEn2: '',
    proveedores: 'ZALKIN',
    fotos: true,
  },
  {
    clave: 'R1032',
    descripcion: 'RESORTES # 24MLSV.0.21/M (H)',
    ubicacion: 'TABLA #4',
    usoEn: 'MONDINI #2 (HARPAK)',
    usoEn2: '',
    proveedores: 'HARPAK',
    fotos: true,
  },
  {
    clave: 'R1033',
    descripcion: 'RESORTES # 24MSLV. 021L70 (H)',
    ubicacion: 'TABLA #4',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'HARPAK',
    fotos: true,
  },
  {
    clave: 'R1034',
    descripcion: 'RESORTES #60609683 (F)',
    ubicacion: 'ANAQ. LAMINA #5 / L#4-C#1',
    usoEn: 'CERRADORA 24/20oz (FOWLER)',
    usoEn2: '',
    proveedores: 'ZALKIN',
    fotos: true,
  },
  {
    clave: 'R1035',
    descripcion: 'RESORTES METALICOS #60235085 (F)',
    ubicacion: 'CAJA PLASTICA #F-1',
    usoEn: 'CERRADORA 24/20oz (FOWLER)',
    usoEn2: '',
    proveedores: 'ZALKIN',
    fotos: true,
  },
  {
    clave: 'R1036',
    descripcion: 'RESORTES METALICOS #60801893 (F)',
    ubicacion: 'CAJA PLASTICA #F-1',
    usoEn: 'CERRADORA 24/20oz (FOWLER)',
    usoEn2: '',
    proveedores: 'ZALKIN',
    fotos: true,
  },
  {
    clave: 'R1037',
    descripcion: 'RODAMIENTO DE BOLA #25BRM8 (H)',
    ubicacion: 'OBSOLETO',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: false,
  },
  {
    clave: 'R1038',
    descripcion: 'SELLOS #28OR4087SIL (H)',
    ubicacion: 'G. SELLOS #1 / L#1-C#1',
    usoEn: 'MONDINIS (HARPAK) Y WALDNER',
    usoEn2: '',
    proveedores: 'HARPAK',
    fotos: true,
  },
  {
    clave: 'R1039',
    descripcion: 'SENSOR DE PROXIMIDAD #1006 (A)',
    ubicacion: 'OBSOLETO',
    usoEn: 'ETIQUET. AXON',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: false,
  },
  {
    clave: 'R1040',
    descripcion: 'SENSOR DE PROXIMIDAD #45LD86PCT3 (H)',
    ubicacion: 'ANAQ. LAMINA #2 / L#4-C#3',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'WENGLOR-HARPAK',
    fotos: true,
  },
  {
    clave: 'R1041',
    descripcion: 'RETEN #X4002444 (EL) (14864 CR USA SKF)',
    ubicacion: 'ANAQ. LAMINA #5 / L#9-C#2',
    usoEn: 'JARABEADORA ELMAR (20/24oz)',
    usoEn2: '',
    proveedores: 'ELMAR 20oz',
    fotos: true,
  },
  {
    clave: 'R1042',
    descripcion: 'SENSOR DE PROX. TELEMECANIQUE (VM1PNOQ) #46B031',
    ubicacion: 'ANAQ. LAMINA #5 / L#1-C#3',
    usoEn: 'CERRADORA 24/20oz (FOWLER)',
    usoEn2: '',
    proveedores: 'ZALKIN',
    fotos: true,
  },
  {
    clave: 'R1043',
    descripcion: 'TAPAS DE GOMA #60753147 (F)',
    ubicacion: 'CAJA PLASTICA #F-2',
    usoEn: 'CERRADORA 24/20oz (FOWLER)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: false,
  },
  {
    clave: 'R1044',
    descripcion: 'TUERCA #60237632 (F)',
    ubicacion: 'CAJA PLASTICA #F-1',
    usoEn: 'CERRADORA 24/20oz (FOWLER)',
    usoEn2: '',
    proveedores: 'ZALKIN',
    fotos: true,
  },
  {
    clave: 'R1045',
    descripcion: 'VALVULA SELENOIDE #2363 24V. SMC (AX)',
    ubicacion: 'OBSOLETO',
    usoEn: 'ETIQUET. AXON',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: false,
  },
  {
    clave: 'R1046',
    descripcion: 'IMAN ELECTRICO X4001540 (X4004534) #BPS33',
    ubicacion: 'ANAQ. LAMINA #5 / L#9-C#1',
    usoEn: 'JARABEADORA ELMAR (20/24oz)',
    usoEn2: '',
    proveedores: 'ELMAR 20oz',
    fotos: true,
  },
  {
    clave: 'R1047',
    descripcion: 'MODULO ELECTRONICO X4001541 AES1135',
    ubicacion: 'ANAQ. LAMINA #5 / L#9-C#1',
    usoEn: 'JARABEADORA ELMAR (20/24oz)',
    usoEn2: '',
    proveedores: 'ELMAR 20oz',
    fotos: true,
  },
  {
    clave: 'R1048',
    descripcion: 'SENSOR DE SEGURIDAD X4003365 #BNS33',
    ubicacion: 'TABLA #33',
    usoEn: 'JARABEADORA ELMAR (20/24oz)',
    usoEn2: '',
    proveedores: 'ELMAR 20oz',
    fotos: true,
  },
  {
    clave: 'R1049',
    descripcion: 'VARIADOR DE FRECUENCIA P.F #22A-D8P7N104',
    ubicacion: 'GABINETE RISOUL (RESGUARDO)',
    usoEn: 'TABLEROS ELECTRICOS',
    usoEn2: '',
    proveedores: 'RISOUL',
    fotos: false,
  },
  {
    clave: 'R1050',
    descripcion: 'BOMBA CENTRIFUGA M-IA2-1/2-15-2 15HP',
    ubicacion: 'OBSOLETO',
    usoEn: 'SIN USO REGISTRADO',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: false,
  },
  {
    clave: 'R1051',
    descripcion: 'VALVULA DIRECCIONAL HIDR. VICKERS #DG4V-3S-2C-M-U-B5-60',
    ubicacion: 'ANAQ. LAM PLOMERIA #8 / L#5',
    usoEn: 'COMPRESORES',
    usoEn2: '',
    proveedores: 'INSTRUMENTACION RG',
    fotos: true,
  },
  {
    clave: 'R1052',
    descripcion: 'BOBINA VICKERS #8507833 110 VOLTS (RG)',
    ubicacion: 'ANAQ. LAM. PLOMERIA #8 / L#4',
    usoEn: 'COMPRESORES',
    usoEn2: '',
    proveedores: 'INSTRUMENTACION RG',
    fotos: true,
  },
  {
    clave: 'R1053',
    descripcion: 'CABLE DE FIBRA OPTICA #60E008 (F)',
    ubicacion: 'ANAQ. LAMINA #5 / L#1-C#3',
    usoEn: 'CERRADORA 24/20oz (FOWLER)',
    usoEn2: '',
    proveedores: 'ZALKIN',
    fotos: true,
  },
  {
    clave: 'R1054',
    descripcion: 'MOTOR ELEC. SIEMENS 1 HP 1750 RPM (RDN)',
    ubicacion: 'TABLA #49',
    usoEn: 'SIN MOVIMIENTO',
    usoEn2: '',
    proveedores: 'RYBSA DEL NORTE',
    fotos: true,
  },
  {
    clave: 'R1055',
    descripcion: 'MOTOR ELEC. SIEMENS 1.5 HP 1750 RPM (RDN)',
    ubicacion: 'TABLA #49',
    usoEn: 'SIN MOVIMIENTO',
    usoEn2: '',
    proveedores: 'RYBSA DEL NORTE',
    fotos: true,
  },
  {
    clave: 'R1056',
    descripcion: 'NAVAJA CIRCULAR # 1651 77x19mm (M)',
    ubicacion: 'OBSOLETO',
    usoEn: 'MATERIAL OBSOLETO TIROMAT',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: false,
  },
  {
    clave: 'R1057',
    descripcion: 'RESORTES METALICOS #60101818 (F)',
    ubicacion: 'CAJA PLASTICA #F-1',
    usoEn: 'CERRADORA 24/20oz (FOWLER)',
    usoEn2: '',
    proveedores: 'ZALKIN',
    fotos: true,
  },
  {
    clave: 'R1058',
    descripcion: 'BANDA SINFIN P/PERFORADORA DE ENZIMATICO',
    ubicacion: 'OBSOLETO',
    usoEn: 'AREA DE ENZIMATICO',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: false,
  },
  {
    clave: 'R1059',
    descripcion: 'ARANDELAS #001543 (A)',
    ubicacion: 'CAJA PLASTICA #C-1',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'ACCRAPLY',
    fotos: true,
  },
  {
    clave: 'R1060',
    descripcion: 'BUJE METALICO #068512 (AC)',
    ubicacion: 'OBSOLETO',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: true,
  },
  {
    clave: 'R1061',
    descripcion: 'BASE AJUSTABLE #035950 (A)',
    ubicacion: 'A. GRAINGER #2 / L#1-C#3',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'ACCRAPLY',
    fotos: true,
  },
  {
    clave: 'R1062',
    descripcion: 'BASES METALICAS #010893 (A)',
    ubicacion: 'OBSOLETO',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: false,
  },
  {
    clave: 'R1063',
    descripcion: 'BASES METALICAS #041448 (A)',
    ubicacion: 'A. GRAINGER #2 / L#1-C#4',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'ACCRAPLY',
    fotos: true,
  },
  {
    clave: 'R1064',
    descripcion: 'BASES METALICAS #068513 (A)',
    ubicacion: 'CAJA PLASTICA #C-1',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'ACCRAPLY',
    fotos: true,
  },
  {
    clave: 'R1065',
    descripcion: 'BASES PLASTICAS #090638 (A)',
    ubicacion: 'OBSOLETO',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: false,
  },
  {
    clave: 'R1066',
    descripcion: 'BUJE #011843 (A)',
    ubicacion: 'CAJA PLASTICA #C-1',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'ACCRAPLY',
    fotos: true,
  },
  {
    clave: 'R1067',
    descripcion: 'BUJES METALICOS #001397 (A)',
    ubicacion: 'OBSOLETO',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: true,
  },
  {
    clave: 'R1068',
    descripcion: 'ESPACIADOR METALICO #031692 (A)',
    ubicacion: 'OBSOLETO',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: false,
  },
  {
    clave: 'R1069',
    descripcion: 'INTERRUPTOR DE BOTON #042384 (A)',
    ubicacion: 'OBSOLETO',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: false,
  },
  {
    clave: 'R1070',
    descripcion: 'LIMPIADORES METALICOS #090639 (A)',
    ubicacion: 'OBSOLETO',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: false,
  },
  {
    clave: 'R1071',
    descripcion: 'MANIVELA #035691 (A)',
    ubicacion: 'A. GRAINGER #2 / L#2-C#3',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'ACCRAPLY',
    fotos: true,
  },
  {
    clave: 'R1072',
    descripcion: 'TIRA DE CAUCHO #147576 (AC)',
    ubicacion: 'A. GRAINGER #2 / L#2-C#2',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'ACCRAPLY',
    fotos: true,
  },
  {
    clave: 'R1073',
    descripcion: 'PANELES MONTABLES #035930 (A)',
    ubicacion: 'OBSOLETO',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: false,
  },
  {
    clave: 'R1074',
    descripcion: 'PASADOR #035519 (A)',
    ubicacion: 'CAJA PLASTICA #C-1',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'ACCRAPLY',
    fotos: true,
  },
  {
    clave: 'R1075',
    descripcion: 'PASADOR #055886 (A)',
    ubicacion: 'CAJA PLASTICA #C-1',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'ACCRAPLY',
    fotos: true,
  },
  {
    clave: 'R1076',
    descripcion: 'PASADOR METALICO #031693 (A)',
    ubicacion: 'OBSOLETO',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: true,
  },
  {
    clave: 'R1077',
    descripcion: 'PASADOR METALICO #035659 (A)',
    ubicacion: 'OBSOLETO',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: true,
  },
  {
    clave: 'R1078',
    descripcion: 'PLATO BAJO METALICO #035641 (A)',
    ubicacion: 'OBSOLETO',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: false,
  },
  {
    clave: 'R1079',
    descripcion: 'PLATO DE MONTADO #031695 (A)',
    ubicacion: 'CAJA PLASTICA #C-1',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'ACCRAPLY',
    fotos: true,
  },
  {
    clave: 'R1080',
    descripcion: 'PLATO EXTERIOR METALICO #039455 (A)',
    ubicacion: 'OBSOLETO',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: false,
  },
  {
    clave: 'R1081',
    descripcion: 'VARIADOR (ENCODER) MOD-H25D-SS-20,000-T10',
    ubicacion: 'ANAQ. LAMINA #6 / L#11-C#1',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'ACCRAPLY',
    fotos: true,
  },
  {
    clave: 'R1082',
    descripcion: 'RESORTES #055874 (A)',
    ubicacion: 'ANAQ. LAMINA #6 / L#10-C#2',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'ACCRAPLY',
    fotos: true,
  },
  {
    clave: 'R1083',
    descripcion: 'RODAMIENTO DE BOLA #014180 (A)',
    ubicacion: 'A. GRAINGER #2 / L#1-C#4',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: false,
  },
  {
    clave: 'R1084',
    descripcion: 'RODILLO CON FLECHA #035681 (A)',
    ubicacion: 'OBSOLETO',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: false,
  },
  {
    clave: 'R1085',
    descripcion: 'VALVULADOR DE VELOCIDADES #012544 (A)',
    ubicacion: 'OBSOLETO',
    usoEn: 'ETIQUETADORA ACCRAPLY (24/20oz)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: false,
  },
  {
    clave: 'R1086',
    descripcion: 'CUBIERTA #60186048 (F)',
    ubicacion: 'TABLA #31',
    usoEn: 'CERRADORA 24/20oz (FOWLER)',
    usoEn2: '',
    proveedores: 'ZALKIN',
    fotos: true,
  },
  {
    clave: 'R1087',
    descripcion: 'MANGUERA 600MM #60316877 (F)',
    ubicacion: 'ANAQ. LAMINA #5 / L#1-C#4',
    usoEn: 'CERRADORA 24/20oz (FOWLER)',
    usoEn2: '',
    proveedores: 'ZALKIN',
    fotos: true,
  },
  {
    clave: 'R1088',
    descripcion: 'CONECTOR DE QUIJADA #60240936 (Z)',
    ubicacion: 'ANAQ. LAMINA #5 / L#1-C#1',
    usoEn: 'CERRADORA 24/20oz (FOWLER)',
    usoEn2: '',
    proveedores: 'ZALKIN',
    fotos: true,
  },
  {
    clave: 'R1089',
    descripcion: 'MANIJAS #60312018 (F)',
    ubicacion: 'ANAQ. LAMINA #5 / L#1-C#3',
    usoEn: 'CERRADORA 24/20oz (FOWLER)',
    usoEn2: '',
    proveedores: 'ZALKIN',
    fotos: true,
  },
  {
    clave: 'R1090',
    descripcion: 'UNION METALICA DELANTERA #60316468 (F)',
    ubicacion: 'CAJA PLASTICA #F-2',
    usoEn: 'CERRADORA 24/20oz (FOWLER)',
    usoEn2: '',
    proveedores: 'ZALKIN',
    fotos: true,
  },
  {
    clave: 'R1091',
    descripcion: 'UNION METALICA TRASERA #60316467 (F)',
    ubicacion: 'CAJA PLASTICA #F-2',
    usoEn: 'CERRADORA 24/20oz (FOWLER)',
    usoEn2: '',
    proveedores: 'ZALKIN',
    fotos: true,
  },
  {
    clave: 'R1092',
    descripcion: 'BRAZOS METALICOS #71SD40700500 (H)',
    ubicacion: 'TABLA #10',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'HARPAK',
    fotos: true,
  },
  {
    clave: 'R1093',
    descripcion: 'BOBINA #31B3024VDC (H)',
    ubicacion: 'CAJA PLASTICA #A-6',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'HARPAK',
    fotos: true,
  },
  {
    clave: 'R1094',
    descripcion: 'CILINDRO #31CBW1020025DE (H)',
    ubicacion: 'ANAQ. LAMINA #2 / L#14-C#4',
    usoEn: 'MONDINIS #3 (HARPAK)',
    usoEn2: '',
    proveedores: 'HARPAK',
    fotos: true,
  },
  {
    clave: 'R1095',
    descripcion: 'TORNILLO DE ACOPLAMIENTO #71LN57625500 (H)',
    ubicacion: 'A. GRAINGER #1 / L#3-C#4',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'HARPAK',
    fotos: true,
  },
  {
    clave: 'R1096',
    descripcion: 'NAVAJA #5943 (A)',
    ubicacion: 'OBSOLETO',
    usoEn: 'ETIQUET. AXON',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: false,
  },
  {
    clave: 'R1097',
    descripcion: 'PLATO DE SELLADO #71SF30401300 (H)',
    ubicacion: 'TABLA #11',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'HARPAK',
    fotos: true,
  },
  {
    clave: 'R1098',
    descripcion: 'PLATOS BASE #60182763 (F)',
    ubicacion: 'TABLA #32',
    usoEn: 'CERRADORA 24/20oz (FOWLER)',
    usoEn2: '',
    proveedores: 'ZALKIN',
    fotos: true,
  },
  {
    clave: 'R1099',
    descripcion: 'PLATOS BASE #60182764 (F)',
    ubicacion: 'TABLA #32',
    usoEn: 'CERRADORA 24/20oz (FOWLER)',
    usoEn2: '',
    proveedores: 'ZALKIN',
    fotos: true,
  },
  {
    clave: 'R1100',
    descripcion: 'RETEN #28G32x42x4 (H)',
    ubicacion: 'CAJA PLASTICA #A-15',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'HARPAK',
    fotos: true,
  },
  {
    clave: 'R1101',
    descripcion: 'RETEN #28G50x58x4 (H)',
    ubicacion: 'ANAQ. LAMINA #2 / L#1-C#1',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'HARPAK',
    fotos: true,
  },
  {
    clave: 'R1102',
    descripcion: 'RETEN #28RS50x60x7 (H)',
    ubicacion: 'ANAQ. LAMINA #2 / L#1-C#1',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'HARPAK',
    fotos: true,
  },
  {
    clave: 'R1103',
    descripcion: 'RETEN #28SD25x35x4 (H)',
    ubicacion: 'CAJA PLASTICA #A-15',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'RIRSA / RYASA',
    fotos: true,
  },
  {
    clave: 'R1104',
    descripcion: 'RETEN DE EMPUJE #28G25x32x4 (H)',
    ubicacion: 'CAJA PLASTICA #A-15',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'HARPAK',
    fotos: true,
  },
  {
    clave: 'R1105',
    descripcion: 'RODILLOS #3038 (A)',
    ubicacion: 'OBSOLETO',
    usoEn: 'ETIQUET. AXON',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: false,
  },
  {
    clave: 'R1106',
    descripcion: 'SELLOS #28OR119SIL (H)',
    ubicacion: 'G. SELLOS #1 / L#1-C#2',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'HARPAK',
    fotos: true,
  },
  {
    clave: 'R1107',
    descripcion: 'SELLOS #28OR123SIL (H)',
    ubicacion: 'GAB. SELLOS #1 / L#1-C#3',
    usoEn: 'MONDINI #2-3 Y 6 (HARPAK)',
    usoEn2: '',
    proveedores: 'HARPAK',
    fotos: true,
  },
  {
    clave: 'R1108',
    descripcion: 'SELLOS #28OR3100SIL (H)',
    ubicacion: 'G. SELLOS #1 / L#1-C#4',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'HARPAK',
    fotos: true,
  },
  {
    clave: 'R1109',
    descripcion: 'SELLOS #28OR3118SIL (H)',
    ubicacion: 'G. SELLOS #1 / L#2-C#1',
    usoEn: 'MONDINI #2 (HARPAK)',
    usoEn2: '',
    proveedores: 'HARPAK',
    fotos: true,
  },
  {
    clave: 'R1110',
    descripcion: 'SELLOS #28OR3150SIL (H)',
    ubicacion: 'G. SELLOS #1 / L#2-C#2',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'HARPAK',
    fotos: true,
  },
  {
    clave: 'R1111',
    descripcion: 'SUJETADORES DE GOMA #60242349 (F) (JUEGOS DE 3 PZAS)',
    ubicacion: 'OBSOLETO',
    usoEn: 'CERRADORA 24/20oz (FOWLER)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: false,
  },
  {
    clave: 'R1112',
    descripcion: 'VALVULA NEUMATICA #31SOV23SOSNC (H)',
    ubicacion: 'ANAQ. LAMINA #2 / L#6-C#4',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'ALFA Y OMEGA',
    fotos: true,
  },
  {
    clave: 'R1113',
    descripcion: 'BASES ROSCADAS #71SV00003000 (71XAAAAI00001) (H)',
    ubicacion: 'TABLA #3',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'HARPAK',
    fotos: true,
  },
  {
    clave: 'R1114',
    descripcion: 'VALVULA DE ENGRASE #28INGM6DRCOR (H)',
    ubicacion: 'CAJA PLASTICA #A-9',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'HARPAK',
    fotos: true,
  },
  {
    clave: 'R1115',
    descripcion: 'CUERDA SILICON #28ORCORD 8SIL (H)',
    ubicacion: 'TABLA #2',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'EMPAQUES IND. GALVAN',
    fotos: true,
  },
  {
    clave: 'R1116',
    descripcion: 'INTERRUPTOR HEMBRA #49CONCNP06FP (H)',
    ubicacion: 'ANAQ. LAMINA #2 / L#3-C#5',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'MAYOREO ELECT. MTY / HARPAK',
    fotos: true,
  },
  {
    clave: 'R1117',
    descripcion: 'INTERRUPTOR MACHO #49CONCNP06FS (H)',
    ubicacion: 'ANAQ. LAMINA #2 / L#3-C#5',
    usoEn: 'MONDINI #6 (HARPAK)',
    usoEn2: '',
    proveedores: 'MAYOREO ELECT. MTY / HARPAK',
    fotos: true,
  },
  {
    clave: 'R1118',
    descripcion: 'MANGUERA HIDRAULICA #349920/355mm 3/8 (H)',
    ubicacion: 'TABLA #7',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: false,
  },
  {
    clave: 'R1119',
    descripcion: 'RESORTES #24MLSD.138.32 (H)',
    ubicacion: 'TABLA #4',
    usoEn: 'MONDINI #2 (HARPAK)',
    usoEn2: '',
    proveedores: 'HARPAK',
    fotos: true,
  },
  {
    clave: 'R1120',
    descripcion: 'SELLOS #2339 (A) (JUEGO)',
    ubicacion: 'OBSOLETO',
    usoEn: 'ETIQUET. AXON',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: false,
  },
  {
    clave: 'R1121',
    descripcion: 'SELLOS #2342 (A) (JUEGO)',
    ubicacion: 'OBSOLETO',
    usoEn: 'ETIQUET. AXON',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: false,
  },
  {
    clave: 'R1122',
    descripcion: 'SELLOS #2381 (A) (JUEGO)',
    ubicacion: 'OBSOLETO',
    usoEn: 'ETIQUET. AXON',
    usoEn2: '',
    proveedores: 'SIN PROVEEDOR',
    fotos: false,
  },
  {
    clave: 'R1123',
    descripcion: 'SELLOS #71SV00002000 (H) (71XAAAAN00001)',
    ubicacion: 'G. SELLOS #3 / L#5-C#1',
    usoEn: 'MONDINI #6 (HARPAK)',
    usoEn2: '',
    proveedores: 'MAVALL / EMPAQUES IND. GALVAN',
    fotos: true,
  },
  {
    clave: 'R1124',
    descripcion: 'GUIAS PLASTICAS #71HB009052S0 (H)',
    ubicacion: 'TABLA #7',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'HARPAK',
    fotos: false,
  },
  {
    clave: 'R1125',
    descripcion: 'MOTOR ELECTRICO #21010042000CV3 (H)',
    ubicacion: 'TABLA #50',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'HARPAK',
    fotos: true,
  },
  {
    clave: 'R1126',
    descripcion: 'VALVULA NEUMATICA #31MAV35VLB00 (H)',
    ubicacion: 'ANAQ. LAMINA #2 / L#6-C#5',
    usoEn: 'MONDINI #2 (HARPAK)',
    usoEn2: '',
    proveedores: 'HARPAK',
    fotos: true,
  },
  {
    clave: 'R1127',
    descripcion: 'BARRA METALICA #25CHIAV22x100F (H)',
    ubicacion: 'CAJA PLASTICA #A-12',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'HARPAK',
    fotos: true,
  },
  {
    clave: 'R1128',
    descripcion: 'MOTOR ELECTRICO #21010046000SV3 (H)',
    ubicacion: 'TABLA #51',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'HARPAK',
    fotos: false,
  },
  {
    clave: 'R1129',
    descripcion: 'MOTOR ELECT. F100LC4 #210400422350A3 (210000000514) (H)',
    ubicacion: 'TABLA #51',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'HARPAK',
    fotos: true,
  },
  {
    clave: 'R1130',
    descripcion: 'RONDANA METALICA #35GUA1/8D11 (H)',
    ubicacion: 'CAJA PLASTICA #A-10',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'HARPAK',
    fotos: true,
  },
  {
    clave: 'R1131',
    descripcion: 'ARRANCADOR MANUAL Y PROTEC.#140M-C2E-B10',
    ubicacion: 'ANAQ. LAMINA #4 / L#3-C#1',
    usoEn: 'TABLEROS ELECTRICOS',
    usoEn2: '',
    proveedores: 'RISOUL',
    fotos: true,
  },
  {
    clave: 'R1132',
    descripcion: 'ARRANCADOR MANUAL Y PROTEC.#140M-C2E-B40',
    ubicacion: 'ANAQ. LAMINA #4 / L#3-C#2',
    usoEn: 'TABLEROS ELECTRICOS',
    usoEn2: '',
    proveedores: 'RISOUL',
    fotos: true,
  },
  {
    clave: 'R1133',
    descripcion: 'ARRANCADOR MANUAL Y PROTEC.#140M-C2E-B63',
    ubicacion: 'ANAQ. LAMINA #4 / L#3-C#2',
    usoEn: 'TABLEROS ELECTRICOS',
    usoEn2: '',
    proveedores: 'RISOUL',
    fotos: true,
  },
  {
    clave: 'R1134',
    descripcion: 'ARRANCADOR MANUAL Y PROTEC. 140M-C2E-C10',
    ubicacion: 'ANAQ. LAMINA #4 / L#3-C#3',
    usoEn: 'TABLEROS ELECTRICOS',
    usoEn2: '',
    proveedores: 'RISOUL',
    fotos: true,
  },
  {
    clave: 'R1135',
    descripcion: 'ARRANCADOR MANUAL Y PROTEC. 140M-C2E-C16',
    ubicacion: 'ANAQ. LAMINA #4 / L#3-C#3',
    usoEn: 'TABLEROS ELECTRICOS',
    usoEn2: '',
    proveedores: 'RISOUL',
    fotos: true,
  },
  {
    clave: 'R1136',
    descripcion: 'CABLE CONECTOR P/SENSOR #889D-F4AC-10 R',
    ubicacion: 'ANAQ. LAMINA #4 / L#1-C#1',
    usoEn: 'MONDINIS',
    usoEn2: '',
    proveedores: 'RISOUL',
    fotos: true,
  },
  {
    clave: 'R1137',
    descripcion: 'CABLE CONECTOR P/SENSOR #889D-F4AC-2 R',
    ubicacion: 'ANAQ. LAMINA #4 / L#1-C#2',
    usoEn: 'MONDINIS',
    usoEn2: '',
    proveedores: 'RISOUL',
    fotos: true,
  },
  {
    clave: 'R1138',
    descripcion: 'CABLE CONECTOR P/SENSOR #889D-F4AC-5 R',
    ubicacion: 'ANAQ. LAMINA #4 / L#1-C#2',
    usoEn: 'MONDINI #4 (HARPAK)',
    usoEn2: '',
    proveedores: 'RISOUL',
    fotos: true,
  },
  {
    clave: 'R1139',
    descripcion: 'SENSOR FOTOELECTRICO A.B # 42KL-U2LB-F4 (R)',
    ubicacion: 'ANAQ. LAMINA #4 / L#6-C#2',
    usoEn: 'BAÑOS',
    usoEn2: '',
    proveedores: 'RISOUL',
    fotos: true,
  },
  {
    clave: 'R1140',
    descripcion: 'INTERRUPTOR DE LIMITE #440P-CDPB12B R',
    ubicacion: 'ANAQ. LAMINA #4 / L#5-C#3',
    usoEn: 'SIN MOVIMIENTO',
    usoEn2: '',
    proveedores: 'RISOUL',
    fotos: true,
  },
  {
    clave: 'R1141',
    descripcion: 'INTERRUPTOR DE SEG. A.B. #440K-T11090 (R',
    ubicacion: 'ANAQ. LAMINA #4 / L#5-C#3',
    usoEn: 'SIN MOVIMIENTO',
    usoEn2: '',
    proveedores: 'RISOUL',
    fotos: true,
  },
  {
    clave: 'R1142',
    descripcion: 'MINI-CONTACTOR 5A. 3 POLO 100-M05NZ243 (100-K05ZJ10) (R)',
    ubicacion: 'ANAQ. LAMINA #4 / L#4-C#5',
    usoEn: 'SISTERNA',
    usoEn2: '',
    proveedores: 'RISOUL',
    fotos: true,
  },
  {
    clave: 'R1143',
    descripcion: 'SENSOR FOTOELECTRICO A.B # 42EF-S1MPA-F4 (R)',
    ubicacion: 'ANAQ. LAMINA #4 / L#6-C#2',
    usoEn: 'MOLENAR',
    usoEn2: '',
    proveedores: 'RISOUL',
    fotos: true,
  },
  {
    clave: 'R1144',
    descripcion: 'ADAPTADOR #60233257 (F)',
    ubicacion: 'ANAQ. LAMINA #5 / L#1-C#5',
    usoEn: 'CERRADORA 24/20oz (FOWLER)',
    usoEn2: '',
    proveedores: 'ZALKIN',
    fotos: true,
  },
  {
    clave: 'R1145',
    descripcion: 'CABLE CONECTOR P/SENSOR #889P-F4AB-5 (R',
    ubicacion: 'ANAQ. LAMINA #4 / L#1-C#3',
    usoEn: 'AUTING',
    usoEn2: '',
    proveedores: 'RISOUL',
    fotos: true,
  },
  {
    clave: 'R1146',
    descripcion: 'BANDA ENTRADA #27FAW5E100x1590 (H)',
    ubicacion: 'ANAQ. LAMINA #11 / L#2',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'LINARAND',
    fotos: true,
  },
  {
    clave: 'R1147',
    descripcion: 'BUJES PLASTICOS #71LA00315600 (H)',
    ubicacion: 'CAJA PLASTICA #A-11',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'HARPAK',
    fotos: true,
  },
  {
    clave: 'R1148',
    descripcion: 'DESLIZADOR DE CABEZA #60230522 (F)',
    ubicacion: 'ANAQ. LAMINA #5 / L#2-C#2',
    usoEn: 'CERRADORA 24/20oz (FOWLER)',
    usoEn2: '',
    proveedores: 'ZALKIN',
    fotos: true,
  },
  {
    clave: 'R1149',
    descripcion: 'ESTRELLA EN TUFNOL PLASTIC #601040807 (Z)',
    ubicacion: 'TABLA #31',
    usoEn: 'CERRADORA 24/20oz (FOWLER)',
    usoEn2: '',
    proveedores: 'ZALKIN',
    fotos: true,
  },
  {
    clave: 'R1150',
    descripcion: 'FUENTE DE PODER #49ET4065 (H)',
    ubicacion: 'TABLA #15',
    usoEn: 'MONDINIS (HARPAK)',
    usoEn2: '',
    proveedores: 'HARPAK',
    fotos: true,
  },
];
