import { useState, useEffect } from 'react';

// 1. EXPORTAMOS LA INTERFAZ
export interface InventoryItem {
  id: string;
  name: string;
  category: string;
  status: 'Available' | 'Out of Stock' | 'Discontinued' | 'Low Stock';
  quantity: number;
  lastUpdated: string;
}

// 2. EXPORTAMOS LAS CATEGORÍAS
export const CATEGORY_OPTIONS = [
  { label: 'Todas las categorías', value: undefined },
  { label: 'Hardware', value: 'Hardware' },
  { label: 'Servidores', value: 'Servidores' },
  { label: 'Redes', value: 'Redes' },
  { label: 'Almacenamiento', value: 'Almacenamiento' },
  { label: 'Seguridad', value: 'Seguridad' },
  { label: 'Energía', value: 'Energía' },
  { label: 'Periféricos', value: 'Periféricos' },
  { label: 'Licencias', value: 'Licencias' },
];

// 3. TUS 50 DATOS FIJOS (MOCK)
export const MOCK_INVENTORY: InventoryItem[] = [
  {
    id: '1',
    name: 'Servidor Rack Dell R740',
    category: 'Servidores',
    status: 'Available',
    quantity: 12,
    lastUpdated: '2024-03-01',
  },
  {
    id: '2',
    name: 'Switch Cisco Catalyst 9300',
    category: 'Redes',
    status: 'Available',
    quantity: 8,
    lastUpdated: '2024-03-02',
  },
  {
    id: '3',
    name: 'Firewall FortiGate 60F',
    category: 'Seguridad',
    status: 'Low Stock',
    quantity: 2,
    lastUpdated: '2024-02-28',
  },
  {
    id: '4',
    name: 'Almacenamiento SAN NetApp',
    category: 'Almacenamiento',
    status: 'Available',
    quantity: 4,
    lastUpdated: '2024-03-05',
  },
  {
    id: '5',
    name: 'UPS APC Smart-UPS 3000VA',
    category: 'Energía',
    status: 'Available',
    quantity: 15,
    lastUpdated: '2024-03-01',
  },
  {
    id: '6',
    name: 'Módulo SFP+ 10Gbps',
    category: 'Redes',
    status: 'Available',
    quantity: 45,
    lastUpdated: '2024-03-04',
  },
  {
    id: '7',
    name: 'Panel Solar Industrial 400W',
    category: 'Energía',
    status: 'Out of Stock',
    quantity: 0,
    lastUpdated: '2024-02-20',
  },
  {
    id: '8',
    name: 'Disco SSD Samsung 870 1TB',
    category: 'Almacenamiento',
    status: 'Available',
    quantity: 30,
    lastUpdated: '2024-03-03',
  },
  {
    id: '9',
    name: 'Router Ubiquiti Dream Machine',
    category: 'Redes',
    status: 'Available',
    quantity: 6,
    lastUpdated: '2024-03-01',
  },
  {
    id: '10',
    name: 'Licencia Windows Server 2022',
    category: 'Licencias',
    status: 'Available',
    quantity: 100,
    lastUpdated: '2024-01-15',
  },
  {
    id: '11',
    name: 'Monitor Dell Ultrasharp 27"',
    category: 'Periféricos',
    status: 'Available',
    quantity: 20,
    lastUpdated: '2024-03-02',
  },
  {
    id: '12',
    name: 'Teclado Mecánico Industrial',
    category: 'Periféricos',
    status: 'Available',
    quantity: 15,
    lastUpdated: '2024-02-25',
  },
  {
    id: '13',
    name: 'Cámara Térmica FLIR',
    category: 'Seguridad',
    status: 'Low Stock',
    quantity: 3,
    lastUpdated: '2024-03-01',
  },
  {
    id: '14',
    name: 'Servidor HP ProLiant DL380',
    category: 'Servidores',
    status: 'Available',
    quantity: 5,
    lastUpdated: '2024-03-02',
  },
  {
    id: '15',
    name: 'Cable Óptico LC-LC 5m',
    category: 'Redes',
    status: 'Available',
    quantity: 60,
    lastUpdated: '2024-03-04',
  },
  {
    id: '16',
    name: 'Inversor de Corriente 2kW',
    category: 'Energía',
    status: 'Available',
    quantity: 7,
    lastUpdated: '2024-02-15',
  },
  {
    id: '17',
    name: 'Sensor de Movimiento IoT',
    category: 'Seguridad',
    status: 'Available',
    quantity: 25,
    lastUpdated: '2024-03-05',
  },
  {
    id: '18',
    name: 'Disco HDD WD Red 4TB',
    category: 'Almacenamiento',
    status: 'Available',
    quantity: 18,
    lastUpdated: '2024-03-01',
  },
  {
    id: '19',
    name: 'Patch Panel 24 Puertos',
    category: 'Redes',
    status: 'Available',
    quantity: 10,
    lastUpdated: '2024-02-28',
  },
  {
    id: '20',
    name: 'Licencia Adobe Creative Cloud',
    category: 'Licencias',
    status: 'Discontinued',
    quantity: 0,
    lastUpdated: '2023-12-20',
  },
  {
    id: '21',
    name: 'Router Mikrotik RB5009',
    category: 'Redes',
    status: 'Available',
    quantity: 12,
    lastUpdated: '2024-03-04',
  },
  {
    id: '22',
    name: 'Access Point Aruba AP-515',
    category: 'Redes',
    status: 'Available',
    quantity: 9,
    lastUpdated: '2024-03-01',
  },
  {
    id: '23',
    name: 'Batería de Reemplazo UPS',
    category: 'Energía',
    status: 'Available',
    quantity: 22,
    lastUpdated: '2024-03-02',
  },
  {
    id: '24',
    name: 'Gabinete Mural 9U',
    category: 'Hardware',
    status: 'Available',
    quantity: 4,
    lastUpdated: '2024-02-20',
  },
  {
    id: '25',
    name: 'Adaptador USB-C a Ethernet',
    category: 'Redes',
    status: 'Available',
    quantity: 50,
    lastUpdated: '2024-03-05',
  },
  {
    id: '26',
    name: 'Impresora Zebra ZT411',
    category: 'Periféricos',
    status: 'Low Stock',
    quantity: 2,
    lastUpdated: '2024-03-01',
  },
  {
    id: '27',
    name: 'Scanner Fujitsu fi-8170',
    category: 'Periféricos',
    status: 'Available',
    quantity: 6,
    lastUpdated: '2024-03-02',
  },
  {
    id: '28',
    name: 'Cámara Domo Hikvision 4K',
    category: 'Seguridad',
    status: 'Available',
    quantity: 14,
    lastUpdated: '2024-03-04',
  },
  {
    id: '29',
    name: 'NVR Dahua 16 Canales',
    category: 'Seguridad',
    status: 'Available',
    quantity: 3,
    lastUpdated: '2024-03-01',
  },
  {
    id: '30',
    name: 'Licencia SQL Server Standard',
    category: 'Licencias',
    status: 'Available',
    quantity: 10,
    lastUpdated: '2024-02-15',
  },
  {
    id: '31',
    name: 'Switch Industrial PoE+',
    category: 'Redes',
    status: 'Available',
    quantity: 5,
    lastUpdated: '2024-03-05',
  },
  {
    id: '32',
    name: 'Convertidor de Medios Fibra',
    category: 'Redes',
    status: 'Available',
    quantity: 12,
    lastUpdated: '2024-03-03',
  },
  {
    id: '33',
    name: 'Kit de Herramientas Red',
    category: 'Hardware',
    status: 'Available',
    quantity: 8,
    lastUpdated: '2024-02-28',
  },
  {
    id: '34',
    name: 'Tester de Cable Fluke',
    category: 'Hardware',
    status: 'Available',
    quantity: 2,
    lastUpdated: '2024-03-01',
  },
  {
    id: '35',
    name: 'Servidor Tower Lenovo ST550',
    category: 'Servidores',
    status: 'Available',
    quantity: 4,
    lastUpdated: '2024-03-02',
  },
  {
    id: '36',
    name: 'Rack de Piso 42U',
    category: 'Hardware',
    status: 'Available',
    quantity: 2,
    lastUpdated: '2024-02-10',
  },
  {
    id: '37',
    name: 'Cable UTP Cat6 305m',
    category: 'Redes',
    status: 'Available',
    quantity: 20,
    lastUpdated: '2024-03-04',
  },
  {
    id: '38',
    name: 'Controlador de Acceso Biométrico',
    category: 'Seguridad',
    status: 'Available',
    quantity: 7,
    lastUpdated: '2024-03-05',
  },
  {
    id: '39',
    name: 'Cerradura Electromagnética',
    category: 'Seguridad',
    status: 'Available',
    quantity: 15,
    lastUpdated: '2024-03-01',
  },
  {
    id: '40',
    name: 'Licencia VMware vSphere',
    category: 'Licencias',
    status: 'Available',
    quantity: 24,
    lastUpdated: '2024-03-02',
  },
  {
    id: '41',
    name: 'Mouse Inalámbrico Logitech',
    category: 'Periféricos',
    status: 'Available',
    quantity: 35,
    lastUpdated: '2024-03-03',
  },
  {
    id: '42',
    name: 'Docking Station Universal',
    category: 'Periféricos',
    status: 'Available',
    quantity: 12,
    lastUpdated: '2024-03-04',
  },
  {
    id: '43',
    name: 'Disco Externo SSD 2TB',
    category: 'Almacenamiento',
    status: 'Available',
    quantity: 10,
    lastUpdated: '2024-03-01',
  },
  {
    id: '44',
    name: 'Memoria RAM DDR4 32GB Server',
    category: 'Hardware',
    status: 'Available',
    quantity: 24,
    lastUpdated: '2024-03-05',
  },
  {
    id: '45',
    name: 'Tarjeta de Red Cuádruple 1Gb',
    category: 'Redes',
    status: 'Low Stock',
    quantity: 3,
    lastUpdated: '2024-02-28',
  },
  {
    id: '46',
    name: 'Sensor de Humedad IoT',
    category: 'Hardware',
    status: 'Available',
    quantity: 40,
    lastUpdated: '2024-03-01',
  },
  {
    id: '47',
    name: 'Gateway IoT Industrial',
    category: 'Redes',
    status: 'Available',
    quantity: 6,
    lastUpdated: '2024-03-02',
  },
  {
    id: '48',
    name: 'PDU Regleta para Rack',
    category: 'Energía',
    status: 'Available',
    quantity: 18,
    lastUpdated: '2024-03-04',
  },
  {
    id: '49',
    name: 'Protector de Voltaje Pro',
    category: 'Energía',
    status: 'Available',
    quantity: 25,
    lastUpdated: '2024-03-05',
  },
  {
    id: '50',
    name: 'Servidor NAS Synology 4-Bay',
    category: 'Almacenamiento',
    status: 'Available',
    quantity: 5,
    lastUpdated: '2024-03-01',
  },
];

// 4. EL HOOK
export const useInventory = () => {
  const [items, setItems] = useState<InventoryItem[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    // Simulamos carga asíncrona pero usando los datos fijos
    const timer = setTimeout(() => {
      setItems(MOCK_INVENTORY);
      setLoading(false);
    }, 300);
    return () => clearTimeout(timer);
  }, []);

  return { items, loading };
};
